apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-nose-tests
      image: python:3.8-slim
      script: |
        #!/bin/sh
        pip install nose
        nosetests
